### ISSUE TITLE
Categories can only be associated with one project

### ISSUE THREAD

**Issue by roy-shiloh** [Hayota-tech/spirng-portfolio-frontend#53]
First of all lets check the categories:
![Screenshot 2023-05-02 at 11 30 12](https://user-images.githubusercontent.com/100530628/235619262-62caee64-7939-4476-a54a-42c57cca7bd0.png)
It seems that only 1 project can be under a category.

# The test:

1. The following project's `Category` is pre-selected as `Behind the Scenes`:
[BTS of Dam Mayo, A Succulent Production](https://spring-strapi-gduf2.ondigitalocean.app/admin/content-manager/collectionType/api::project.project/43)

![image](https://user-images.githubusercontent.com/100530628/235619811-38381491-f4f1-4e25-9453-995c2bbb89ba.png)

2. I apply the same `Category` to another project:
[Baseball - Mixtiles](https://spring-strapi-gduf2.ondigitalocean.app/admin/content-manager/collectionType/api::project.project/136)

![image](https://user-images.githubusercontent.com/100530628/235619897-e28fcab2-65a1-4bb9-8b5e-fbe3da5b1979.png)

3. As you can see, the `Category` disappears from the first Project:

![image](https://user-images.githubusercontent.com/100530628/235620022-018b1004-d1fd-4332-a7bf-a64b752617cd.png)

---

As you can see, the project has now took the place as the only project that can be associated with the category.

![Screenshot 2023-05-02 at 11 29 29](https://user-images.githubusercontent.com/100530628/235620387-b1466ec7-8eb5-422f-868c-2f99cef99b1a.png)

Conclusion: Categories can only be associated with one project

**Comment by amir-ben-shimol** [comment]
Issue resolved on `aviv-shiloh-backend` pr #2
